spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/ngrx
spring.datasource.driverClassName=org.postgresql.Driver
# PLEASE VERIFY YOUR DATABASE CREDENTIALS BELOW
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# Disable H2 console as we are using PostgreSQL
spring.h2.console.enabled=false
